-- MySQL Script generated by MySQL Workbench
-- Mon May 30 14:34:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kev_especiesmarinas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kev_especiesmarinas` ;

-- -----------------------------------------------------
-- Schema kev_especiesmarinas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kev_especiesmarinas` DEFAULT CHARACTER SET utf8 ;
USE `kev_especiesmarinas` ;

-- -----------------------------------------------------
-- Table `kev_especiesmarinas`.`tiburon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kev_especiesmarinas`.`tiburon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `habitat` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `profundidad` INT NULL,
  `pelagico` VARCHAR(45) NULL,
  `tiempo_navegacion` INT NULL,
  `nubosidad` VARCHAR(45) NULL,
  `fuerza_viento` VARCHAR(45) NULL,
  `direccion_viento` VARCHAR(45) NULL,
  `hora_llegada` VARCHAR(45) NULL,
  `embarcaciones_zona` INT NULL,
  `temperatura_superf` INT NULL,
  `tipo_cebo` VARCHAR(45) NULL,
  `parasitos` VARCHAR(45) NULL,
  `presencia_anzuelos` VARCHAR(45) NULL,
  `num_anzuelos` INT NULL,
  `medidas` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kev_especiesmarinas`.`raya`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kev_especiesmarinas`.`raya` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `habitat` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `profundidad` INT NULL,
  `pelagico` VARCHAR(45) NULL,
  `tiempo_navegacion` INT NULL,
  `nubosidad` VARCHAR(45) NULL,
  `fuerza_viento` VARCHAR(45) NULL,
  `direccion_viento` VARCHAR(45) NULL,
  `hora_llegada` VARCHAR(45) NULL,
  `embarcaciones_zona` INT NULL,
  `temperatura_superf` INT NULL,
  `tipo_cebo` VARCHAR(45) NULL,
  `parasitos` VARCHAR(45) NULL,
  `presencia_anzuelos` VARCHAR(45) NULL,
  `num_anzuelos` INT NULL,
  `medidas` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kev_especiesmarinas`.`molusco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kev_especiesmarinas`.`molusco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `habitat` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `profundidad` INT NULL,
  `tiempo_navegacion` INT NULL,
  `nubosidad` VARCHAR(45) NULL,
  `fuerza_viento` VARCHAR(45) NULL,
  `direccion_viento` VARCHAR(45) NULL,
  `hora_llegada` VARCHAR(45) NULL,
  `embarcaciones_zona` INT NULL,
  `temperatura_superf` INT NULL,
  `medidas` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kev_especiesmarinas`.`alga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kev_especiesmarinas`.`alga` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `habitat` VARCHAR(45) NULL,
  `profundidad` INT NULL,
  `tiempo_navegacion` INT NULL,
  `nubosidad` VARCHAR(45) NULL,
  `fuerza_viento` VARCHAR(45) NULL,
  `direccion_viento` VARCHAR(45) NULL,
  `hora_llegada` VARCHAR(45) NULL,
  `embarcaciones_zona` INT NULL,
  `temperatura_superf` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
